### ISSUE TITLE
Error Get Token,

### ISSUE THREAD

**Issue by kartono21** [azishapidin/laravel-midtrans-example#1]
Hi Bang Azis,

Maaf mau nanyak..ini kok gak dapet" get token yah..

ini dalem controller function token

`$transaction_details = array(
        'order_id'      => $request->id,
        'gross_amount'  => $request->total
    );

    $items = [
        array(
            'id'        => 'item1',
            'price'     => $request->total-4000,
            'quantity'  => 1,
            'name'      => 'Total Biaya SPP'
        ),
        array(
            'id'        => 'item2',
            'price'     => 4000,
            'quantity'  => 1,
            'name'      => 'Biaya Admin Transfer'
        )
    ];

    $murid = Student::where('id', $id)
    ->first();

    // Populate customer's billing address
    $billing_address = array(
        'first_name'    => $murid->name,
        'last_name'     => "",
        'address'       => "Bali",
        'city'          => "Bali",
        'postal_code'   => "51161",
        'phone'         => $murid->telp,
        'country_code'  => 'IDN'
      );

    // Populate customer's shipping address
    $shipping_address = $billing_address;

    // Populate customer's Info
    $customer_details = array(
        'first_name'      => $murid->name,
        'last_name'       => "",
        'email'           => $murid->email,
        'phone'           => $murid->telp,
        'billing_address' => $billing_address,
        'shipping_address'=> $shipping_address
        );

    // Data yang akan dikirim untuk request redirect_url.
    $credit_card['secure'] = true;
    //ser save_card true to enable oneclick or 2click
    //$credit_card['save_card'] = true;

    $time = time();
    $custom_expiry = array(
        'start_time' => date("Y-m-d H:i:s O",$time),
        'unit'       => 'hour',
        'duration'   => 4
    );

    $transaction_data = array(
        'transaction_details'=> $transaction_details,
        'item_details'       => $items,
        'customer_details'   => $customer_details,
        'credit_card'        => $credit_card,
        'expiry'             => $custom_expiry
    );

    try
    {
        //$snap_token = $midtrans->getSnapToken($transaction_data);
        $snap_token = Veritrans_Snap::getSnapToken($transaction_data);
        //return redirect($vtweb_url);
        //$this->response['snap_token'] = $snapToken;
        echo $snap_token;
    }
    catch (Exception $e)
    {
        return $e->getMessage;
    }`

ini javascript

`$('#pay-button').click(function (event) {
  event.preventDefault();
  $.ajax({

  url: './snaptoken/invoice={{$invoice}}&amount={{$total+4000}}',
  cache: false,
    success: function(data) {
      console.log('token = '+data);
      var resultType = document.getElementById('result-type');
      var resultData = document.getElementById('result-data');

      function changeResult(type,data){
        $("#result-type").val(type);
        $("#result-data").val(JSON.stringify(data));
        //resultType.innerHTML = type;
        //resultData.innerHTML = JSON.stringify(data);
      }
      snap.pay(data, {
        onSuccess: function(result){
          changeResult('success', result);
          console.log(result.status_message);
          console.log(result);
          $("#payment-form").submit();
        },
        onPending: function(result){
          changeResult('pending', result);
          console.log(result.status_message);
          $("#payment-form").submit();
        },
        onError: function(result){
          changeResult('error', result);
          console.log(result.status_message);
          $("#payment-form").submit();
        }
      });
    }
  });
});`

bisa dibantu bang

**Comment by azishapidin** [comment]
Apakah Midtrans Client Key dan Server Key nya sudah di konfigurasi?
